//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcedurluDbFirst_Proje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SatıslarEntities3 : DbContext
    {
        public SatıslarEntities3()
            : base("name=SatıslarEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Araclar> Araclars { get; set; }
        public virtual DbSet<Musteriler> Musterilers { get; set; }
        public virtual DbSet<Personeller> Personellers { get; set; }
        public virtual DbSet<Sevkiyatlar> Sevkiyatlars { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual int AEkle(string aractur, Nullable<int> aracKapasite, string aracSofor)
        {
            var aracturParameter = aractur != null ?
                new ObjectParameter("Aractur", aractur) :
                new ObjectParameter("Aractur", typeof(string));
    
            var aracKapasiteParameter = aracKapasite.HasValue ?
                new ObjectParameter("AracKapasite", aracKapasite) :
                new ObjectParameter("AracKapasite", typeof(int));
    
            var aracSoforParameter = aracSofor != null ?
                new ObjectParameter("AracSofor", aracSofor) :
                new ObjectParameter("AracSofor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AEkle", aracturParameter, aracKapasiteParameter, aracSoforParameter);
        }
    
        public virtual ObjectResult<AListele_Result> AListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AListele_Result>("AListele");
        }
    
        public virtual int ASil(Nullable<int> aracNo)
        {
            var aracNoParameter = aracNo.HasValue ?
                new ObjectParameter("AracNo", aracNo) :
                new ObjectParameter("AracNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ASil", aracNoParameter);
        }
    
        public virtual int AYenile(Nullable<int> aracNo, string aractur, Nullable<int> aracKapasite, string aracSofor)
        {
            var aracNoParameter = aracNo.HasValue ?
                new ObjectParameter("AracNo", aracNo) :
                new ObjectParameter("AracNo", typeof(int));
    
            var aracturParameter = aractur != null ?
                new ObjectParameter("Aractur", aractur) :
                new ObjectParameter("Aractur", typeof(string));
    
            var aracKapasiteParameter = aracKapasite.HasValue ?
                new ObjectParameter("AracKapasite", aracKapasite) :
                new ObjectParameter("AracKapasite", typeof(int));
    
            var aracSoforParameter = aracSofor != null ?
                new ObjectParameter("AracSofor", aracSofor) :
                new ObjectParameter("AracSofor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AYenile", aracNoParameter, aracturParameter, aracKapasiteParameter, aracSoforParameter);
        }
    
        public virtual int MEkle(string sevkiyatId, string musteriAdSoyad, string adres, string telefon, string mail, string odemeDurumu, Nullable<int> personelNo)
        {
            var sevkiyatIdParameter = sevkiyatId != null ?
                new ObjectParameter("SevkiyatId", sevkiyatId) :
                new ObjectParameter("SevkiyatId", typeof(string));
    
            var musteriAdSoyadParameter = musteriAdSoyad != null ?
                new ObjectParameter("MusteriAdSoyad", musteriAdSoyad) :
                new ObjectParameter("MusteriAdSoyad", typeof(string));
    
            var adresParameter = adres != null ?
                new ObjectParameter("Adres", adres) :
                new ObjectParameter("Adres", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            var odemeDurumuParameter = odemeDurumu != null ?
                new ObjectParameter("OdemeDurumu", odemeDurumu) :
                new ObjectParameter("OdemeDurumu", typeof(string));
    
            var personelNoParameter = personelNo.HasValue ?
                new ObjectParameter("PersonelNo", personelNo) :
                new ObjectParameter("PersonelNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MEkle", sevkiyatIdParameter, musteriAdSoyadParameter, adresParameter, telefonParameter, mailParameter, odemeDurumuParameter, personelNoParameter);
        }
    
        public virtual ObjectResult<MListele_Result> MListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MListele_Result>("MListele");
        }
    
        public virtual int MSil(Nullable<int> musteriNo)
        {
            var musteriNoParameter = musteriNo.HasValue ?
                new ObjectParameter("MusteriNo", musteriNo) :
                new ObjectParameter("MusteriNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MSil", musteriNoParameter);
        }
    
        public virtual int MYenile(Nullable<int> musteriNo, string sevkiyatId, string musteriAdSoyad, string adres, string telefon, string mail, string odemeDurumu, Nullable<int> personelNo)
        {
            var musteriNoParameter = musteriNo.HasValue ?
                new ObjectParameter("MusteriNo", musteriNo) :
                new ObjectParameter("MusteriNo", typeof(int));
    
            var sevkiyatIdParameter = sevkiyatId != null ?
                new ObjectParameter("SevkiyatId", sevkiyatId) :
                new ObjectParameter("SevkiyatId", typeof(string));
    
            var musteriAdSoyadParameter = musteriAdSoyad != null ?
                new ObjectParameter("MusteriAdSoyad", musteriAdSoyad) :
                new ObjectParameter("MusteriAdSoyad", typeof(string));
    
            var adresParameter = adres != null ?
                new ObjectParameter("Adres", adres) :
                new ObjectParameter("Adres", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            var odemeDurumuParameter = odemeDurumu != null ?
                new ObjectParameter("OdemeDurumu", odemeDurumu) :
                new ObjectParameter("OdemeDurumu", typeof(string));
    
            var personelNoParameter = personelNo.HasValue ?
                new ObjectParameter("PersonelNo", personelNo) :
                new ObjectParameter("PersonelNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MYenile", musteriNoParameter, sevkiyatIdParameter, musteriAdSoyadParameter, adresParameter, telefonParameter, mailParameter, odemeDurumuParameter, personelNoParameter);
        }
    
        public virtual int PEkle(string personelAdSoyad, string adres, string telefon, string mail)
        {
            var personelAdSoyadParameter = personelAdSoyad != null ?
                new ObjectParameter("PersonelAdSoyad", personelAdSoyad) :
                new ObjectParameter("PersonelAdSoyad", typeof(string));
    
            var adresParameter = adres != null ?
                new ObjectParameter("Adres", adres) :
                new ObjectParameter("Adres", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PEkle", personelAdSoyadParameter, adresParameter, telefonParameter, mailParameter);
        }
    
        public virtual ObjectResult<PListele_Result> PListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PListele_Result>("PListele");
        }
    
        public virtual int PSil(Nullable<int> personelNo)
        {
            var personelNoParameter = personelNo.HasValue ?
                new ObjectParameter("PersonelNo", personelNo) :
                new ObjectParameter("PersonelNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PSil", personelNoParameter);
        }
    
        public virtual int PYenile(Nullable<int> personelNo, string personelAdSoyad, string adres, string telefon, string mail)
        {
            var personelNoParameter = personelNo.HasValue ?
                new ObjectParameter("PersonelNo", personelNo) :
                new ObjectParameter("PersonelNo", typeof(int));
    
            var personelAdSoyadParameter = personelAdSoyad != null ?
                new ObjectParameter("PersonelAdSoyad", personelAdSoyad) :
                new ObjectParameter("PersonelAdSoyad", typeof(string));
    
            var adresParameter = adres != null ?
                new ObjectParameter("Adres", adres) :
                new ObjectParameter("Adres", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PYenile", personelNoParameter, personelAdSoyadParameter, adresParameter, telefonParameter, mailParameter);
        }
    
        public virtual int SEkle(string sevkiyatAdi, string sevkiyatAlimNoktasi, string sevkiyatUlasimNoktasi, string mesafe, Nullable<decimal> mesafeTutar, Nullable<int> aracNo, Nullable<int> musteriNo)
        {
            var sevkiyatAdiParameter = sevkiyatAdi != null ?
                new ObjectParameter("SevkiyatAdi", sevkiyatAdi) :
                new ObjectParameter("SevkiyatAdi", typeof(string));
    
            var sevkiyatAlimNoktasiParameter = sevkiyatAlimNoktasi != null ?
                new ObjectParameter("SevkiyatAlimNoktasi", sevkiyatAlimNoktasi) :
                new ObjectParameter("SevkiyatAlimNoktasi", typeof(string));
    
            var sevkiyatUlasimNoktasiParameter = sevkiyatUlasimNoktasi != null ?
                new ObjectParameter("SevkiyatUlasimNoktasi", sevkiyatUlasimNoktasi) :
                new ObjectParameter("SevkiyatUlasimNoktasi", typeof(string));
    
            var mesafeParameter = mesafe != null ?
                new ObjectParameter("Mesafe", mesafe) :
                new ObjectParameter("Mesafe", typeof(string));
    
            var mesafeTutarParameter = mesafeTutar.HasValue ?
                new ObjectParameter("MesafeTutar", mesafeTutar) :
                new ObjectParameter("MesafeTutar", typeof(decimal));
    
            var aracNoParameter = aracNo.HasValue ?
                new ObjectParameter("AracNo", aracNo) :
                new ObjectParameter("AracNo", typeof(int));
    
            var musteriNoParameter = musteriNo.HasValue ?
                new ObjectParameter("MusteriNo", musteriNo) :
                new ObjectParameter("MusteriNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SEkle", sevkiyatAdiParameter, sevkiyatAlimNoktasiParameter, sevkiyatUlasimNoktasiParameter, mesafeParameter, mesafeTutarParameter, aracNoParameter, musteriNoParameter);
        }
    
        public virtual ObjectResult<SListele_Result> SListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SListele_Result>("SListele");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int SSil(Nullable<int> sevkiyatNo)
        {
            var sevkiyatNoParameter = sevkiyatNo.HasValue ?
                new ObjectParameter("SevkiyatNo", sevkiyatNo) :
                new ObjectParameter("SevkiyatNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SSil", sevkiyatNoParameter);
        }
    
        public virtual int SYenile(Nullable<int> sevkiyatNo, string sevkiyatAdi, string sevkiyatAlimNoktasi, string sevkiyatUlasimNoktasi, string mesafe, Nullable<decimal> mesafeTutar, Nullable<int> aracNo, Nullable<int> musteriNo)
        {
            var sevkiyatNoParameter = sevkiyatNo.HasValue ?
                new ObjectParameter("SevkiyatNo", sevkiyatNo) :
                new ObjectParameter("SevkiyatNo", typeof(int));
    
            var sevkiyatAdiParameter = sevkiyatAdi != null ?
                new ObjectParameter("SevkiyatAdi", sevkiyatAdi) :
                new ObjectParameter("SevkiyatAdi", typeof(string));
    
            var sevkiyatAlimNoktasiParameter = sevkiyatAlimNoktasi != null ?
                new ObjectParameter("SevkiyatAlimNoktasi", sevkiyatAlimNoktasi) :
                new ObjectParameter("SevkiyatAlimNoktasi", typeof(string));
    
            var sevkiyatUlasimNoktasiParameter = sevkiyatUlasimNoktasi != null ?
                new ObjectParameter("SevkiyatUlasimNoktasi", sevkiyatUlasimNoktasi) :
                new ObjectParameter("SevkiyatUlasimNoktasi", typeof(string));
    
            var mesafeParameter = mesafe != null ?
                new ObjectParameter("Mesafe", mesafe) :
                new ObjectParameter("Mesafe", typeof(string));
    
            var mesafeTutarParameter = mesafeTutar.HasValue ?
                new ObjectParameter("MesafeTutar", mesafeTutar) :
                new ObjectParameter("MesafeTutar", typeof(decimal));
    
            var aracNoParameter = aracNo.HasValue ?
                new ObjectParameter("AracNo", aracNo) :
                new ObjectParameter("AracNo", typeof(int));
    
            var musteriNoParameter = musteriNo.HasValue ?
                new ObjectParameter("MusteriNo", musteriNo) :
                new ObjectParameter("MusteriNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SYenile", sevkiyatNoParameter, sevkiyatAdiParameter, sevkiyatAlimNoktasiParameter, sevkiyatUlasimNoktasiParameter, mesafeParameter, mesafeTutarParameter, aracNoParameter, musteriNoParameter);
        }
    }
}
